# Generated by Django 4.2.2 on 2024-04-08 04:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_title', models.CharField(max_length=255, unique=True, verbose_name='card_title')),
            ],
            options={
                'db_table': 'card',
                'ordering': ['card_title'],
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=128, verbose_name='full_name')),
                ('birthday', models.DateTimeField(verbose_name='birthday')),
                ('sex', models.CharField(choices=[('М', 'М'), ('Ж', 'Ж')], default='М', max_length=1, verbose_name='sex')),
                ('phone', models.CharField(max_length=64, verbose_name='phone')),
            ],
            options={
                'db_table': 'client',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hall_title', models.CharField(max_length=128, unique=True, verbose_name='hall_title')),
                ('equipment', models.TextField(blank=True, null=True, verbose_name='equipment')),
            ],
            options={
                'db_table': 'hall',
                'ordering': ['hall_title'],
            },
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=128, verbose_name='full_name')),
                ('sex', models.CharField(choices=[('М', 'М'), ('Ж', 'Ж')], default='М', max_length=1, verbose_name='sex')),
                ('phone', models.CharField(max_length=64, verbose_name='phone')),
            ],
            options={
                'db_table': 'instructor',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='Kind',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind_title', models.CharField(max_length=128, unique=True, verbose_name='kind_title')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='kind_price')),
            ],
            options={
                'db_table': 'kind',
                'ordering': ['kind_title'],
            },
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party_title', models.CharField(max_length=96, unique=True, verbose_name='party_title')),
            ],
            options={
                'db_table': 'party',
                'ordering': ['party_title'],
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(verbose_name='start_date')),
                ('finish_date', models.DateTimeField(verbose_name='finish_date')),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_hall', to='club.hall')),
                ('kind', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_kind', to='club.kind')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_party', to='club.party')),
            ],
            options={
                'db_table': 'schedule',
                'ordering': ['start_date', 'finish_date'],
            },
        ),
        migrations.CreateModel(
            name='ScheduleInstructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_instructor_instructor', to='club.instructor')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_instructor_schedule', to='club.schedule')),
            ],
            options={
                'db_table': 'schedule_instructor',
                'ordering': ['schedule'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateTimeField(verbose_name='payment_date')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='payment_amount')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_client', to='club.client')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_party', to='club.party')),
            ],
            options={
                'db_table': 'payment',
                'ordering': ['payment_date'],
            },
        ),
        migrations.CreateModel(
            name='PartyMembers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='party_members_client', to='club.client')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='party_members_party', to='club.party')),
            ],
            options={
                'db_table': 'party_members',
                'ordering': ['party'],
            },
        ),
        migrations.AddIndex(
            model_name='party',
            index=models.Index(fields=['party_title'], name='party_party_t_e0adb2_idx'),
        ),
        migrations.AddField(
            model_name='instructor',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='instructor_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='client',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_card', to='club.card'),
        ),
        migrations.AddIndex(
            model_name='scheduleinstructor',
            index=models.Index(fields=['schedule', 'instructor'], name='schedule_in_schedul_711d59_idx'),
        ),
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['start_date', 'finish_date'], name='schedule_start_d_023a95_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['party'], name='payment_party_i_62404b_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['client'], name='payment_client__f8afe5_idx'),
        ),
        migrations.AddIndex(
            model_name='partymembers',
            index=models.Index(fields=['party'], name='party_membe_party_i_764f1a_idx'),
        ),
        migrations.AddIndex(
            model_name='partymembers',
            index=models.Index(fields=['client'], name='party_membe_client__d94432_idx'),
        ),
        migrations.AddIndex(
            model_name='instructor',
            index=models.Index(fields=['full_name'], name='instructor_full_na_b8f753_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['full_name'], name='client_full_na_f03115_idx'),
        ),
    ]
